Add missing dependency on generated header files
Specifically the GetSerial.h is generated from the srv file and is
needed by astra_driver.h. Without this there is nothing to ensure that
GetSerial.h is generated before the code that uses it gets compiled and
can fail as follows:
Errors     << astra_camera:make .../build/logs/astra_camera/build.make.000.log
In file included from
.../build/src/ros_astra_camera/src/astra_device.cpp:39:0:
.../build/src/ros_astra_camera/include/astra_camera/astra_driver.h:55:36:
fatal error: astra_camera/GetSerial.h: No such file or directory